from django.urls import path
from credit import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
	path('home/', views.HomeView.as_view(), name='home'),
    path('clients/', views.ClientList.as_view(), name='client-list'),
    path('credits/', views.CreditList.as_view(), name='credit-list'),
    path('paiements/', views.PaiementList.as_view(), name='paiement-list'),
    path('planning-paiements/', views.PlanningPaiementList.as_view(), name='planning-paiement-list'),
    path('garanties/', views.GarantieList.as_view(), name='garantie-list'),
    path('historiques/', views.HistoriquePaiementList.as_view(), name='historique-list'),
    path('clients/detail/<int:id>/', views.ClientDetail.as_view(), name='client-detail'),
    path('credits/detail/<int:id>/', views.CreditDetail.as_view(), name='credit-detail'),
    path('planning-paiements/detail/<int:id>/', views.PlanningDetail.as_view(), name='planning-detail'),
    path('paiements/detail/<int:id>/', views.PaiementDetail.as_view(), name='paiement-detail'),
    path('garanties/detail/<int:id>/', views.GarantieDetail.as_view(), name='garantie-detail'),
    path('historiques/detail/<int:id>/', views.HistoriqueDetail.as_view(), name='historique-detail'),
    path('clients/ajout/', views.ClientCreate.as_view(), name='client-add'),
    path('credits/ajout/', views.CreditCreate.as_view(), name='credit-add'),
    path('planning-paiements/ajout/', views.PlanningCreate.as_view(), name='planning-add'),
    path('paiements/ajout/', views.PaiementCreate.as_view(), name='paiement-add'),
    path('garanties/ajout/', views.GarantieCreate.as_view(), name='garantie-add'),
    path('clients/modification/<int:id>/', views.ClientUpdate.as_view(), name='client-update'),
    path('credits/modification/<int:id>/', views.CreditUpdate.as_view(), name='credit-update'),
    path('planning-paiements/modification/<int:id>/', views.PlanningUpdate.as_view(), name='planning-update'),
    path('paiements/modification/<int:id>/', views.PaiementUpdate.as_view(), name='paiement-update'),
    path('garanties/modification/<int:id>/', views.GarantieUpdate.as_view(), name='garantie-update'),
    path('clients/suppression/<int:id>/', views.ClientDelete.as_view(), name='client-delete'),
    path('credits/suppression/<int:id>/', views.CreditDelete.as_view(), name='credit-delete'),
    path('planning-paiements/suppression/<int:id>/', views.PlanningDelete.as_view(), name='planning-delete'),
    path('paiements/suppression/<int:id>/', views.PaiementDelete.as_view(), name='paiement-delete'),
    path('garanties/suppression/<int:id>/', views.GarantieDelete.as_view(), name='garantie-delete'),
    path('historiques/suppression/<int:id>/', views.HistoriqueDelete.as_view(), name='historique-delete'),
]