# Generated by Django 5.1.2 on 2024-10-27 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_naissance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_interet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duree_mois', models.IntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('en cours', 'En cours'), ('payé', 'Payé'), ('retard', 'En retard')], default='actif', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='credit.client')),
            ],
        ),
        migrations.CreateModel(
            name='Garantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_garantie', models.CharField(max_length=50)),
                ('valeur_estimee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garanties', to='credit.credit')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('mode_paiement', models.CharField(choices=[('cheque', 'Chèque'), ('carte', 'Carte bancaire'), ('espece', 'Espèces'), ('virement', 'Virement bancaire')], max_length=10)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='credit.credit')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ancien_statut', models.CharField(choices=[('payée', 'Payée'), ('attente', 'En attente'), ('retard', 'En retard')], max_length=10)),
                ('nouveau_statut', models.CharField(choices=[('payée', 'Payée'), ('attente', 'En attente'), ('retard', 'En retard')], max_length=10)),
                ('remarque', models.TextField(blank=True)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='credit.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningPaiements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_echeance', models.IntegerField()),
                ('montant_echeance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('payée', 'Payée'), ('attente', 'En attente'), ('retard', 'En retard')], default='attente', max_length=10)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='credit.credit')),
            ],
        ),
        migrations.AddField(
            model_name='paiement',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='credit.planningpaiements'),
        ),
    ]
