# Generated by Django 5.1.2 on 2024-11-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_alter_client_id_alter_credit_id_alter_garantie_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planningpaiements',
            unique_together={('credit', 'numero_echeance')},
        ),
    ]
