# Generated by Django 5.1.2 on 2024-11-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_credit_montant_restant'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='montant_credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='credit',
            name='montant_restant',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
