# Generated by Django 5.1.2 on 2024-11-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_credit_montant_credit_alter_credit_montant_restant'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantie',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('utilisée', 'Utilisée'), ('expirée', 'Expirée')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='credit',
            name='montant_restant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
