# Generated by Django 5.1.2 on 2024-11-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0009_alter_garantie_options_garantie_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquepaiement',
            name='ancien_statut',
            field=models.CharField(choices=[('payé', 'Payé'), ('attente', 'En attente'), ('retard', 'En retard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historiquepaiement',
            name='nouveau_statut',
            field=models.CharField(choices=[('payé', 'Payé'), ('attente', 'En attente'), ('retard', 'En retard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='planningpaiements',
            name='statut',
            field=models.CharField(choices=[('payé', 'Payé'), ('attente', 'En attente'), ('retard', 'En retard')], default='attente', max_length=10),
        ),
    ]
