# Generated by Django 5.1.2 on 2024-11-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0010_alter_historiquepaiement_ancien_statut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiquepaiement',
            name='ancien_statut',
        ),
        migrations.RemoveField(
            model_name='historiquepaiement',
            name='nouveau_statut',
        ),
    ]
